name: main
on:
  - pull_request
  - push
jobs:
  main:
    name: ${{matrix.node}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - run: npm install --global npm@latest
      - run: npm install
      - run: npm run build
      - run: npm test
    strategy:
      matrix:
        node:
          - 12
          - 14
          - 16
