name: main
on:
  - pull_request
  - push
jobs:
  test:
    name: ${{matrix.node}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - run: npm install --global npm@latest
      - run: npm install-ci-test
      - run: npm run format && git diff --exit-code
